version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: prueba_tecnica_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: prueba_tecnica
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: prueba_tecnica_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:12345@db:5432/prueba_tecnica
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "alembic upgrade head &&
             fastapi run src/main.py --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
