"""primera migracion

Revision ID: 9e6b9ecd5c6e
Revises: 1d42e48fddbc
Create Date: 2026-07-09 23:32:47.188920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6b9ecd5c6e'
down_revision: Union[str, Sequence[str], None] = '1d42e48fddbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cbamimport',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('eori_number', sa.String(length=17), nullable=False),
    sa.Column('declarant_legal_name', sa.String(length=255), nullable=False),
    sa.Column('declarant_address', sa.Text(), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('competent_authority', sa.String(length=100), nullable=False),
    sa.Column('cbam_account_number', sa.String(length=100), nullable=False),
    sa.Column('data_owner', sa.String(length=255), nullable=False),
    sa.Column('taric_code', sa.String(length=10), nullable=True),
    sa.Column('cn_code', sa.String(length=8), nullable=False),
    sa.Column('goods_description', sa.Text(), nullable=False),
    sa.Column('sector_category', sa.String(length=100), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('import_volume', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date_of_importation', sa.Date(), nullable=False),
    sa.Column('country_of_origin', sa.String(length=100), nullable=False),
    sa.Column('customs_declaration_ref', sa.String(length=100), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('notes_comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cbamimport')
    # ### end Alembic commands ###
